<?php

return [
    'parents' => array(
            array(
                "name" => "not_eligible_cause",
                "short_name" => "not_eligible_cause",
                 "code" => "10",
            ),
             array(
                "name" => "Payment Type",
                "short_name" => "payment_type",
                "code" => "50",
            ),
            array(
                "name" => "Lot Type",
                "short_name" => "lot_type",
                "code" => "59",
            ),
             array(
                "name" => "Payment Mode",
                "short_name" => "payment_mode",
                "code" => "520",
            ),
             array(
                "name" => "Payment Lot Status Common",
                "short_name" => "payment_lot_status_common",
                "code" => config('payment_lot.parent_status_code.common'),
            ),
             array(
                "name" => "Payment Lot Status SBI",
                "short_name" => "payment_lot_status_sbi",
                "code" => config('payment_lot.parent_status_code.sbi'),
            ),
             array(
                "name" => "Payment Lot Status IFMS",
                "short_name" => "payment_lot_status_ifms",
                "code" => config('payment_lot.parent_status_code.ifms'),
            ),
            array(
                "name" => "Payment Lot Status Bandhan",
                "short_name" => "payment_lot_status_bandhan",
                "code" => config('payment_lot.parent_status_code.bandhan'),
            ),
             array(
                "name" => "Validation Lot Status",
                "short_name" => "validation_lot_status",
                "code" => "522",
            ),
             array(
                "name" => "Payment Lot Configuration",
                "short_name" => "payment_lot_configuration",
                "code" => "523",
            ),
            array(
                "name" => "Validation Lot Configuration",
                "short_name" => "validation_lot_configuration",
                "code" => "524",
            ),
             array(
                "name" => "Validation Mode",
                "short_name" => "validation_mode",
                "code" => "525",
            ),
             array(
                "name" => "SBI Status Code",
                "short_name" => "sbi_status_code",
                "code" => "526",
            ),
        ),
    'childs' => array(
            array(
                "name" => "SC",
                "short_name" => "sc",
                "parent_short_code" => "caste",
                "code" => "171",
            ),
            array(
                "name" => "ST",
                "short_name" => "st",
                "parent_short_code" => "caste",
                 "code" => "172",
            ),
            array(
                "name" => "General",
                "short_name" => "general",
                "parent_short_code" => "caste",
                 "code" => "173",
            ),
            array(
                "name" => "NEXT LEVEL ROLE ID OPERATOR",
                "short_name" => "next_level_role_id_operator",
                "parent_short_code" => "next_level_role_id",
                 "code" => "21",
            ),
            array(
                "name" => "NEXT LEVEL ROLE ID VERIFIER",
                "short_name" => "next_level_role_id_verifier",
                "parent_short_code" => "next_level_role_id",
                 "code" => "22",
            ),
            array(
                "name" => "NEXT LEVEL ROLE ID APPROVER",
                "short_name" => "next_level_role_id_approver",
                "parent_short_code" => "next_level_role_id",
                 "code" => "23",
            ),
            array(
                "name" => "NEXT LEVEL ROLE ID RECOMANDER",
                "short_name" => "next_level_role_id_recomander",
                "parent_short_code" => "next_level_role_id",
                 "code" => "24",
            ),
            array(
                "name" => "Marital Status Unmarried",
                "short_name" => "marital_status_unmarried",
                "parent_short_code" => "marital_status",
                 "code" => "31",
            ),
            array(
                "name" => "Marital Status Married",
                "short_name" => "marital_status_married",
                "parent_short_code" => "marital_status",
                 "code" => "32",
            ),
            array(
                "name" => "Marital Status Seperated",
                "short_name" => "marital_status_seperated",
                "parent_short_code" => "marital_status",
                 "code" => "33",
            ),
            array(
                "name" => "Marital Status Widow",
                "short_name" => "marital_status_widow",
                "parent_short_code" => "marital_status",
                 "code" => "34",
            ),
            array(
                "name" => "Marital Status Widower",
                "short_name" => "marital_status_widower",
                "parent_short_code" => "marital_status",
                 "code" => "35",
            ),
            array(
                "name" => "Entry Type Normal",
                "short_name" => "entry_type_normal",
                "parent_short_code" => "entry_type",
                 "code" => "41",
            ),
            array(
                "name" => "Entry Type Duare Sarkar",
                "short_name" => "entry_type_duare_sarkar",
                "parent_short_code" => "entry_type",
                 "code" => "42",
            ),
            array(
                "name" => "Male",
                "short_name" => "male",
                "parent_short_code" => "gender",
                 "code" => "51",
            ),
            array(
                "name" => "Female",
                "short_name" => "female",
                "parent_short_code" => "gender",
                 "code" => "52",
            ),
            array(
                "name" => "Other",
                "short_name" => "other",
                "parent_short_code" => "gender",
                 "code" => "53",
            ),
            array(
                "name" => "Orthopedically Handicapped",
                "short_name" => "OH",
                "parent_short_code" => "disablity_type",
                 "code" => "61",
            ),
            array(
                "name" => "Visually Handicapped",
                "short_name" => "VH",
                "parent_short_code" => "disablity_type",
                 "code" => "62",
            ),
            array(
                "name" => "Mental illness",
                "short_name" => "MI",
                "parent_short_code" => "disablity_type",
                 "code" => "63",
            ),
            array(
                "name" => "Mental Retardation",
                "short_name" => "MR",
                "parent_short_code" => "disablity_type",
                 "code" => "64",
            ),
            array(
                "name" => "Mutiple Disablities",
                "short_name" => "MD",
                "parent_short_code" => "disablity_type",
                 "code" => "65",
            ),
            array(
                "name" => "Leprosy Cured",
                "short_name" => "LC",
                "parent_short_code" => "disablity_type",
                 "code" => "66",
            ),
            array(
                "name" => "Nervous Disorder",
                "short_name" => "ND",
                "parent_short_code" => "disablity_type",
                 "code" => "67",
            ),
            array(
                "name" => "Others",
                "short_name" => "others",
                "parent_short_code" => "disablity_type",
                 "code" => "68",
            ),
            array(
                "name" => "AAY",
                "short_name" => "AAY",
                "parent_short_code" => "ration_cat",
                 "code" => "71",
            ),
            array(
                "name" => "OHH",
                "short_name" => "OHH",
                "parent_short_code" => "ration_cat",
                 "code" => "72",
            ),
            array(
                "name" => "RKSY 1",
                "short_name" => "RKSY 1",
                "parent_short_code" => "ration_cat",
                 "code" => "73",
            ),
            array(
                "name" => "RKSY 2",
                "short_name" => "RKSY 2",
                "parent_short_code" => "ration_cat",
                 "code" => "74",
            ),
            array(
                "name" => "SPHH",
                "short_name" => "SPHH",
                "parent_short_code" => "ration_cat",
                 "code" => "75",
            ),
            array(
                "name" => "PHH",
                "short_name" => "PHH",
                "parent_short_code" => "ration_cat",
                 "code" => "76",
            ),
            array(
                "name" => "Central Govt",
                "short_name" => "Central Govt",
                "parent_short_code" => "pension_body",
                 "code" => "81",
            ),
            array(
                "name" => "State Govt",
                "short_name" => "State Govt",
                "parent_short_code" => "pension_body",
                 "code" => "82",
            ),
            array(
                "name" => "Local Administration",
                "short_name" => "Local Administration",
                "parent_short_code" => "pension_body",
                 "code" => "83",
            ),
            array(
                "name" => "Govt. Aided Organization",
                "short_name" => "Govt. Aided Organization",
                "parent_short_code" => "pension_body",
                 "code" => "84",
            ),
            array(
                "name" => "NSAP Old Age",
                "short_name" => "NSAP Old Age",
                "parent_short_code" => "social_pension_cat",
                 "code" => "91",
            ),
            array(
                "name" => "NSAP Widow Pension",
                "short_name" => "NSAP Widow Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "92",
            ),
            array(
                "name" => "NSAP Disability Pension",
                "short_name" => "NSAP Disability Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "93",
            ),
            array(
                "name" => "Old Age Pension",
                "short_name" => "Old Age Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "94",
            ),
            array(
                "name" => "Widow Pension",
                "short_name" => "Widow Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "95",
            ),
            array(
                "name" => "Disability Pension",
                "short_name" => "Disability Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "96",
            ),
            array(
                "name" => "Lok Prasar Prakalpa",
                "short_name" => "Lok Prasar Prakalpa",
                "parent_short_code" => "social_pension_cat",
                 "code" => "97",
            ),
            array(
                "name" => "Fishermans Old Age Pension",
                "short_name" => "Fisherman Old Age Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "98",
            ),
            array(
                "name" => "Farmers Old Age Pension",
                "short_name" => "Farmers Old Age Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "99",
            ),
            array(
                "name" => "Artisan/Weaver Old Age Pension",
                "short_name" => "Artisan/Weaver Old Age Pension",
                "parent_short_code" => "social_pension_cat",
                 "code" => "910",
            ),
         array(
                "name" => "Hinduism",
                "short_name" => "Hinduism",
                "parent_short_code" => "religion",
                 "code" => "111",
            ),
            array(
                "name" => "Islam",
                "short_name" => "Islam",
                "parent_short_code" => "religion",
                 "code" => "112",
            ),
            array(
                "name" => "Christianity",
                "short_name" => "Christianity",
                "parent_short_code" => "religion",
                 "code" => "113",
            ),
            array(
                "name" => "Sikhism",
                "short_name" => "Sikhism",
                "parent_short_code" => "religion",
                 "code" => "114",
            ),
            array(
                "name" => "Buddhism",
                "short_name" => "Buddhism",
                "parent_short_code" => "religion",
                 "code" => "115",
            ),
            array(
                "name" => "Jainism",
                "short_name" => "Jainism",
                "parent_short_code" => "religion",
                 "code" => "116",
            ),
            array(
                "name" => "Unaffiliated",
                "short_name" => "Unaffiliated",
                "parent_short_code" => "religion",
                 "code" => "117",
            ),
            array(
                "name" => "Others",
                "short_name" => "Others",
                "parent_short_code" => "religion",
                 "code" => "118",
            ),
            array(
                "name" => "Duplicate Bank Account Number",
                "short_name" => "DUP BANK",
                "parent_short_code" => "rejection_cause",
                 "code" => "121",
            ),
            array(
                "name" => "Duplicate Aadhaar Number",
                "short_name" => "DUP AADHAAR",
                "parent_short_code" => "rejection_cause",
                 "code" => "122",
            ),
            array(
                "name" => "Bank Passbook Not Uploaded or Not Clearly Visible",
                "short_name" => "VisibleBankDocument",
                "parent_short_code" => "rejection_cause",
                 "code" => "123",
            ),
            array(
                "name" => "Aadhaar Document Not Uploaded or Not Clearly Visible",
                "short_name" => "VisibleAadhaarDocument",
                "parent_short_code" => "rejection_cause",
                 "code" => "124",
            ),
            array(
                "name" => "Caste Cerificate Document Not Uploaded or Not Clearly Visible",
                "short_name" => "VisibleCasteDocument",
                "parent_short_code" => "rejection_cause",
                 "code" => "125",
            ),
            array(
                "name" => "Caste Cerificate Number Not Avilable",
                "short_name" => "CasteCerificate",
                "parent_short_code" => "rejection_cause",
                 "code" => "126",
            ),
            array(
                "name" => "DOB Invalid",
                "short_name" => "DOBINVALID",
                "parent_short_code" => "rejection_cause",
                 "code" => "127",
            ),
            array(
                "name" => "Some of the Document not clearly visible",
                "short_name" => "somedocnotvisible",
                "parent_short_code" => "rejection_cause",
                 "code" => "128",
            ),
            array(
                "name" => "Rejection due to Death",
                "short_name" => "deathcasue",
                "parent_short_code" => "rejection_cause",
                 "code" => "129",
            ),
            array(
                "name" => "Father",
                "short_name" => "relationshipfather",
                "parent_short_code" => "relationship",
                 "code" => "131",
            ),
            array(
                "name" => "Mother",
                "short_name" => "relationshipmother",
                "parent_short_code" => "relationship",
                 "code" => "132",
            ),
            array(
                "name" => "Spouse",
                "short_name" => "relationshipspouse",
                "parent_short_code" => "relationship",
                 "code" => "133",
            ),
            array(
                "name" => "NO AADHAAR NUMBER",
                "short_name" => "no_aadhaar_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "141",
            ),
            array(
                "name" => "NO MOBILE NUMBER",
                "short_name" => "no_mobile_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "142",
            ),
            array(
                "name" => "NO AADHAAR DOCUMENT",
                "short_name" => "no_aadhaar_document",
                "parent_short_code" => "incomplete_details",
                 "code" => "143",
            ),
            array(
                "name" => "BANK PASSBOOK NOT AVAILABLE",
                "short_name" => "bank_passbook_not_available",
                "parent_short_code" => "incomplete_details",
                 "code" => "144",
            ),
            array(
                "name" => "NAME VALIDATION  FAILED IN BANK",
                "short_name" => "name_validation_failed_in_bank",
                "parent_short_code" => "incomplete_details",
                 "code" => "145",
            ),
            array(
                "name" => "ACCOUNT NUMBER VALIDATION  FAILED IN BANK",
                "short_name" => "account_number_validation_failed_in_bank",
                "parent_short_code" => "incomplete_details",
                 "code" => "146",
            ),
            array(
                "name" => "NO CASTE CERTIFICATE NUMBER",
                "short_name" => "no_caste_certificate_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "147",
            ),
            array(
                "name" => "NO CASTE DOCUMENT",
                "short_name" => "no_caste_document",
                "parent_short_code" => "incomplete_details",
                 "code" => "148",
            ),
            array(
                "name" => "DUPLICATE AADHAAR NUMBER",
                "short_name" => "duplicate_aadhaar_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "149",
            ),
            array(
                "name" => "DUPLICATE MOBILE NUMBER",
                "short_name" => "duplicate_mobile_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "1410",
            ),
            array(
                "name" => "DUPLICATE BANK ACCOUNT NUMBER",
                "short_name" => "duplicate_bank_account_number",
                "parent_short_code" => "incomplete_details",
                 "code" => "1411",
            ),
             array(
                "name" => "Minor Mismatch(40% - 89%)",
                "short_name" => "minor_mismatch_40_89",
                "parent_short_code" => "incomplete_details",
                 "code" => "1412",
            ),
             array(
                "name" => "Minor Mismatch(90% - 100%)",
                "short_name" => "minor_mismatch_90_100",
                "parent_short_code" => "incomplete_details",
                 "code" => "1413",
            ),
             array(
                "name" => "PDS Mismatch",
                "short_name" => "pds_mismatch",
                "parent_short_code" => "incomplete_details",
                 "code" => "1414",
            ),
            array(
                "name" => "Payment Falied",
                "short_name" => "payment_failed",
                "parent_short_code" => "incomplete_details",
                "code" => "1415",
            ),
            array(
                "name" => "STATE OFFICE",
                "short_name" => "state_office",
                "parent_short_code" => "office_type",
                 "code" => "151",
            ),
            array(
                "name" => "DISTRICT OFFICE",
                "short_name" => "district_office",
                "parent_short_code" => "office_type",
                 "code" => "152",
            ),
            array(
                "name" => "BLOCK OFFICE",
                "short_name" => "block_office",
                "parent_short_code" => "office_type",
                 "code" => "153",
            ),
            array(
                "name" => "SUBDIVISION OFFICE",
                "short_name" => "subdivision_office",
                "parent_short_code" => "office_type",
                 "code" => "154",
            ),
            array(
                "name" => "MUNICIPALITY OFFICE",
                "short_name" => "municipality_office",
                "parent_short_code" => "office_type",
                 "code" => "155",
            ),
            array(
                "name" => "PANCHAYAT OFFICE",
                "short_name" => "panchayat_office",
                "parent_short_code" => "office_type",
                 "code" => "156",
            ),
            array(
                "name" => "WARD OFFICE",
                "short_name" => "ward_office",
                "parent_short_code" => "office_type",
                 "code" => "159",
            ),
            array(

                "name" => "Passport size profile photo",
                "short_name" => "profile_photo_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "161",
            ),
            array(
                "name" => "Copy of Caste Certificate",
                "short_name" => "caste_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "162",
            ),
            array(
                "name" => "Copy of Disability Certificate from Appropriate Authority",
                "short_name" => "disability_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "163",
            ),
            array(
                "name" => "Copy of Digital Ration Card",
                "short_name" => "ration_card_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "164",
            ),
            array(
                "name" => "Copy of Aadhaar Card",
                "short_name" => "aadhaar_card_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "165",
            ),
            array(
                "name" => "Copy of EPIC/ Voter Id",
                "short_name" => "voter_id_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "166",
            ),
            array(
                "name" => "Copy of Residential Certificate(Self Declaration)",
                "short_name" => "residential_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "167",
            ),
            array(
                "name" => "Copy of Income Certificate(Self Declaration)",
                "short_name" => "income_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "168",
            ),
            array(
                "name" => "Copy of Bank Pass book",
                "short_name" => "bank_pass_book_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "169",
            ),
            array(
                "name" => "Others, please specify",
                "short_name" => "others_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1610",
            ),
            array(
                "name" => "Copy of Death Certificate",
                "short_name" => "death_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1611",
            ),
            array(
                "name" => "Copy of ineligibility letter",
                "short_name" => "ineligibility_letter_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1612",
            ),
            array(
                "name" => "Copy of Digital Certificate from Appropriate Authority",
                "short_name" => "digital_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1613",
            ),
            array(
                "name" => "Birth registration Certificate",
                "short_name" => "birth_registration_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1614",
            ),
            array(
                "name" => "Husband's Death Certificate",
                "short_name" => "husband_death_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1615",
            ),
            array(
                "name" => "Copy of Khatian(ROR)/Deed",
                "short_name" => "khatian_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1616",
            ),
            array(
                "name" => "Copy of PAN Card",
                "short_name" => "pan_card_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1617",
            ),
            array(
                "name" => "Certificate from school",
                "short_name" => "certificate_from_school_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1618",
            ),
            array(
                "name" => "Certificate from Secondary Education Board",
                "short_name" => "Secondary_education_board_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1619",
            ),
            array(
                "name" => "Certificate from recognized educational institution",
                "short_name" => "educational_institution_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1620",
            ),
            array(
                "name" => "Certificate from the Sabhapati of a PanchayatSamity",
                "short_name" => "sabhapati_panchayatSamity_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1621",
            ),
            array(
                "name" => "Certificate from the chairman of a municipal corporation ( in case of a urban area)",
                "short_name" => "chairman_municipal_corporation_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1622",
            ),
            array(
                "name" => "Certificate from a Government Medical Officer",
                "short_name" => "medical_officer_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1623",
            ),
            array(
                "name" => "Aadhaar consent form",
                "short_name" => "aadhaar_consent_form_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1624",
            ),
            array(
                "name" => "Investigation report",
                "short_name" => "investigation_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1625",
            ),
            array(
                "name" => "Self-Declaration of Applicant that she is not remarried",
                "short_name" => "remarried_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1626",
            ),
            array(
                "name" => "Age Proof documets",
                "short_name" => "age_proof_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1627",
            ),
            array(
                "name" => "Copy of Confirmation of Bank Account Validation Form",
                "short_name" => "bank_account_validation_form_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1628",
            ),
            array(
                "name" => "Supporting Age Document",
                "short_name" => "age_document_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1629",
            ),
            array(
                "name" => "Reasoned Order",
                "short_name" => "reasoned_order_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1630",
            ),
            array(
                "name" => "Enquiry Document",
                "short_name" => "enquiry_document_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1631",
            ),
            array(
                "name" => "Life Certificate",
                "short_name" => "life_certificate_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1632",
            ),
            array(
                "name" => "Supporting Document for Payment Enable or Disable ",
                "short_name" => "payment_enable_disable_enc",
                "parent_short_code" => "ENCDETAILS",
                 "code" => "1633",
            ),
             array(
                "name" => "Account Base",
                "short_name" => "acc_base",
                "parent_short_code" => "payment_type",
                 "code" => "5001",
            ),
             array(
                "name" => "ABPS Base",
                "short_name" => "abps_base",
                "parent_short_code" => "payment_type",
                 "code" => "5002",
            ),
            array(
                "name" => "Regular Lot",
                "short_name" => "regular_lot",
                "parent_short_code" => "lot_type",
                 "code" => "5901",
            ),
             array(
                "name" => "Arrer Lot",
                "short_name" => "arrer_lot",
                "parent_short_code" => "lot_type",
                 "code" => "5902",
            ),
            array(
                "name" => "SBI",
                "short_name" => "sbi",
                "parent_short_code" => "payment_mode",
                 "code" => "5201",
            ),
             array(
                "name" => "IFMS",
                "short_name" => "ifms",
                "parent_short_code" => "payment_mode",
                 "code" => "5202",
            ),
            array(
                "name" => "IFMS V3",
                "short_name" => "ifms-v3",
                "parent_short_code" => "payment_mode",
                 "code" => "5203",
            ),
             array(
                "name" => "Bandhan",
                "short_name" => "Bandhan",
                "parent_short_code" => "payment_mode",
                 "code" => "5204",
            ),
            array(
                "name" => "Sir Mark",
                "short_name" => "not_eligible_cause_sir",
                "parent_short_code" => "not_eligible_cause",
                "code" => "5205",
            ),
             array(
                "name" => "Others",
                "short_name" => "not_eligible_cause_oth",
                "parent_short_code" => "not_eligible_cause",
                 "code" => "5206",
            ),
            array(
                "name" => "Not Generated",
                "short_name" => "payment_lot_status_not_generated",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.not_generated'),
            ),
            array(
                "name" => "Generated",
                "short_name" => "payment_lot_status_generated",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.generated'),
            ),
            array(
                "name" => "Push",
                "short_name" => "payment_lot_status_push",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.push'),
            ),
            array(
                "name" => "Success",
                "short_name" => "payment_lot_status_success",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.success'),
            ),
            array(
                "name" => "Failed",
                "short_name" => "payment_lot_status_failed",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.failed'),
            ),
            array(
                "name" => "DEFUNCT",
                "short_name" => "payment_lot_status_defunct",
                "parent_short_code" => "payment_lot_status_common",
                 "code" => config('payment_lot.status.common.defunct'),
            ),
             array(
                "name" => "Generated but yet not Signed",
                "short_name" => "payment_lot_status_not_signed",
                "parent_short_code" => "payment_lot_status_sbi",
                 "code" => config('payment_lot.status.sbi.not_signed'),
            ),
            array(
                "name" => "Generated and Signed but yet not Pushed",
                "short_name" => "payment_lot_status_generated_and_signed",
                "parent_short_code" => "payment_lot_status_sbi",
                 "code" => config('payment_lot.status.sbi.generated_and_signed'),
            ),
            array(
                "name" => "Generated and Pushed but Response Pending",
                "short_name" => "payment_lot_status_generated_and_pushed",
                "parent_short_code" => "payment_lot_status_sbi",
                 "code" => config('payment_lot.status.sbi.generated_and_pushed'),
            ),
             array(
                "name" => "Generated,Pushed and Response Received",
                "short_name" => "payment_lot_status_generated_pushed_response_received",
                "parent_short_code" => "payment_lot_status_sbi",
                 "code" => config('payment_lot.status.sbi.generated_pushed_response_received'),
            ),
           

             array(
                "name" => "Not Generated",
                "short_name" => "validation_lot_status_not_generated",
                "parent_short_code" => "validation_lot_status",
                 "code" => "52201",
            ),
             array(
                "name" => "Generated but yet not Pushed",
                "short_name" => "validation_lot_status_generated",
                "parent_short_code" => "validation_lot_status",
                 "code" => "52202",
            ),
            array(
                "name" => "Generated and Pushed but Response Pending",
                "short_name" => "validation_lot_status_generated_and_pushed",
                "parent_short_code" => "validation_lot_status",
                 "code" => "52203",
            ),
             array(
                "name" => "Generated,Pushed and Response Received",
                "short_name" => "validation_lot_status_generated_pushed_response_received",
                "parent_short_code" => "validation_lot_status",
                 "code" => "52204",
            ),
            array(
                "name" => "Generated but Yet not Push to IFMS",
                "short_name" => "payment_lot_status_generated_ifms",
                "parent_short_code" => "payment_lot_status_ifms",
                 "code" => config('payment_lot.status.common.generated'),
            ),
            array(
                "name" => "Push to IFMS but Acknowledgement Pending ",
                "short_name" => "payment_lot_status_push_ifms",
                "parent_short_code" => "payment_lot_status_ifms",
                 "code" => config('payment_lot.status.common.push'),
            ),
            array(
                "name" => "Acknowledgement Received but RBI Report Pening ",
                "short_name" => "payment_lot_status_ack_ifms",
                "parent_short_code" => "payment_lot_status_ifms",
                 "code" => config('payment_lot.status.ifms.dotdone'),
            ),
            
           
            array(
                "name" => "All Action Done",
                "short_name" => "payment_lot_status_all_action_done ifms",
                "parent_short_code" => "payment_lot_status_ifms",
                 "code" => config('payment_lot.status.common.response'),
            ),
        
           
             array(
                "name" => "Enable/Disable Payment Lot Create Option",
                "short_name" => "payment_lot_create_enable_disable",
                "parent_short_code" => "payment_lot_configuration",
                 "code" => "52301",
            ),
             array(
                "name" => "Enable/Disable Payment Lot Push Option",
                "short_name" => "payment_lot_push_enable_disable",
                "parent_short_code" => "payment_lot_configuration",
                 "code" => "52302",
            ),
             array(
                "name" => "Enable/Disable Payment Lot Response Option",
                "short_name" => "payment_lot_response_enable_disable",
                "parent_short_code" => "payment_lot_configuration",
                 "code" => "52303",
            ),
             array(
                "name" => "Enable/Disable Validation Lot Create Option",
                "short_name" => "validation_lot_create_enable_disable",
                "parent_short_code" => "validation_lot_configuration",
                 "code" => "52401",
            ),
             array(
                "name" => "Enable/Disable Validation Lot Push Option",
                "short_name" => "validation_lot_push_enable_disable",
                "parent_short_code" => "validation_lot_configuration",
                 "code" => "52402",
            ),
             array(
                "name" => "Enable/Disable Validation Lot Response Option",
                "short_name" => "validation_lot_response_enable_disable",
                "parent_short_code" => "validation_lot_configuration",
                 "code" => "52403",
            ),
            array(
                "name" => "Account Validation",
                "short_name" => "acc_base_validation",
                "parent_short_code" => "validation_mode",
                 "code" => "52501",
            ),
             array(
                "name" => "DBT Validation",
                "short_name" => "dbt_validation",
                "parent_short_code" => "validation_mode",
                 "code" => "52502",
            ),
             array(
                "name" => "SUCCESS",
                "short_name" => "S00",
                "parent_short_code" => "sbi_status_code",
                "code" => "52601",
            ),
             array(
                "name" => "PAYMENTS INITIATED",
                "short_name" => "S01",
                "parent_short_code" => "sbi_status_code",
                "code" => "52602",
            ),
             array(
                "name" => "ACCOUNT DOES NOT EXISTS",
                "short_name" => "E01",
                "parent_short_code" => "sbi_status_code",
                "code" => "52603",
            ),
             array(
                "name" => "INVALID ACCOUNT",
                "short_name" => "E02",
                "parent_short_code" => "sbi_status_code",
                "code" => "52604",
            ),
             array(
                "name" => "ACCOUNT RESTRICTED",
                "short_name" => "E03",
                "parent_short_code" => "sbi_status_code",
                "code" => "52605",
            ),
             array(
                "name" => "INSUFFICIENT BALANCE",
                "short_name" => "E04",
                "parent_short_code" => "sbi_status_code",
                "code" => "52606",
            ),
             array(
                "name" => "ACCOUNT STOPPED",
                "short_name" => "E05",
                "parent_short_code" => "sbi_status_code",
                "code" => "52607",
            ),
             array(
                "name" => "ACCOUNT CLOSED",
                "short_name" => "E06",
                "parent_short_code" => "sbi_status_code",
                "code" => "52608",
            ),
             array(
                "name" => "OPERATIONS SUSPENDED",
                "short_name" => "E07",
                "parent_short_code" => "sbi_status_code",
                "code" => "52609",
            ),
             array(
                "name" => "ACCOUNT HOLDER EXPIRED",
                "short_name" => "E08",
                "parent_short_code" => "sbi_status_code",
                "code" => "52610",
            ),
             array(
                "name" => "ACCOUNT UNDER LITIGATION",
                "short_name" => "E09",
                "parent_short_code" => "sbi_status_code",
                "code" => "52611",
            ),
             array(
                "name" => "GARNISHI ORDER RECEIVED",
                "short_name" => "E10",
                "parent_short_code" => "sbi_status_code",
                "code" => "52612",
            ),
             array(
                "name" => "KYC PENDING",
                "short_name" => "E11",
                "parent_short_code" => "sbi_status_code",
                "code" => "52613",
            ),
             array(
                "name" => "FISRT TRANSACTION IN CASH OR SELF CHEQUE",
                "short_name" => "E12",
                "parent_short_code" => "sbi_status_code",
                "code" => "52614",
            ),
             array(
                "name" => "BENEFICIARY NAME DIFFERS",
                "short_name" => "E13",
                "parent_short_code" => "sbi_status_code",
                "code" => "52615",
            ),
             array(
                "name" => "CREDIT TO NRI ACCOUNT",
                "short_name" => "E14",
                "parent_short_code" => "sbi_status_code",
                "code" => "52616",
            ),
             array(
                "name" => "OVERDRAFT NOT ALLOWED OR LIMIT EXCEEDED",
                "short_name" => "E15",
                "parent_short_code" => "sbi_status_code",
                "code" => "52617",
            ),
             array(
                "name" => "CREDIT LIMIT EXCEEDS",
                "short_name" => "E16",
                "parent_short_code" => "sbi_status_code",
                "code" => "52618",
            ),
             array(
                "name" => "CUSTOMER TURNED MAJOR NOW",
                "short_name" => "E17",
                "parent_short_code" => "sbi_status_code",
                "code" => "52619",
            ),
             array(
                "name" => "WELCOME KIT NOT ISSUED",
                "short_name" => "E18",
                "parent_short_code" => "sbi_status_code",
                "code" => "52620",
            ),
             array(
                "name" => "INTER BRANCH TRANSACTION NOT ALLOWED",
                "short_name" => "E19",
                "parent_short_code" => "sbi_status_code",
                "code" => "52621",
            ),
             array(
                "name" => "INVALID RECEIVER IFSC CODE",
                "short_name" => "E20",
                "parent_short_code" => "sbi_status_code",
                "code" => "52622",
            ),
             array(
                "name" => "PARTICIPANT NOT MAPPED TO - APBS PRESENTATION",
                "short_name" => "E21",
                "parent_short_code" => "sbi_status_code",
                "code" => "52623",
            ),
             array(
                "name" => "INVALID AADHAAR",
                "short_name" => "E22",
                "parent_short_code" => "sbi_status_code",
                "code" => "52624",
            ),
             array(
                "name" => "AADHAAR NOT MAPPED TO ACCOUNT",
                "short_name" => "E23",
                "parent_short_code" => "sbi_status_code",
                "code" => "52625",
            ),
             array(
                "name" => "INACTIVE AADHAAR",
                "short_name" => "E24",
                "parent_short_code" => "sbi_status_code",
                "code" => "52626",
            ),
             array(
                "name" => "NETWORK FAILURE",
                "short_name" => "E25",
                "parent_short_code" => "sbi_status_code",
                "code" => "52627",
            ),
             array(
                "name" => "TRANSACTION PENDING",
                "short_name" => "E26",
                "parent_short_code" => "sbi_status_code",
                "code" => "52628",
            ),
             array(
                "name" => "DUPLICATE TRANSACTION",
                "short_name" => "E27",
                "parent_short_code" => "sbi_status_code",
                "code" => "52629",
            ),
             array(
                "name" => "RECALLED BY AGENCY",
                "short_name" => "E28",
                "parent_short_code" => "sbi_status_code",
                "code" => "52630",
            ),
             array(
                "name" => "MANDATE CANCELLED",
                "short_name" => "E29",
                "parent_short_code" => "sbi_status_code",
                "code" => "52631",
            ),
             array(
                "name" => "INCORRECT STATE CODE",
                "short_name" => "E30",
                "parent_short_code" => "sbi_status_code",
                "code" => "52632",
            ),
             array(
                "name" => "INCORRECT DISTRICT CODE",
                "short_name" => "E31",
                "parent_short_code" => "sbi_status_code",
                "code" => "52633",
            ),
             array(
                "name" => "HASH VALUE OF DIGITAL SIGNATURE MISMATCH",
                "short_name" => "E32",
                "parent_short_code" => "sbi_status_code",
                "code" => "52634",
            ),
             array(
                "name" => "DEBIT REFERENCE AND FILE NAME ARE DIFFERENT",
                "short_name" => "E33",
                "parent_short_code" => "sbi_status_code",
                "code" => "52635",
            ),
             array(
                "name" => "FILE NOT DIGITALLY SIGNED",
                "short_name" => "E34",
                "parent_short_code" => "sbi_status_code",
                "code" => "52636",
            ),
             array(
                "name" => "INVALID FILE NAME",
                "short_name" => "E35",
                "parent_short_code" => "sbi_status_code",
                "code" => "52637",
            ),
             array(
                "name" => "DUPLICATE FILE",
                "short_name" => "E36",
                "parent_short_code" => "sbi_status_code",
                "code" => "52638",
            ),
             array(
                "name" => "RECORD COUNT AND AMOUNT GIVEN UNDER DEBIT TAG DOES NOT MATCH WITH ACTUAL RECORDS IN THE FILE",
                "short_name" => "E37",
                "parent_short_code" => "sbi_status_code",
                "code" => "52639",
            ),
             array(
                "name" => "DEBIT REFERENCE DOES NOT EXISTS",
                "short_name" => "E38",
                "parent_short_code" => "sbi_status_code",
                "code" => "52640",
            ),
             array(
                "name" => "CREDIT REFERENCE DOES NOT EXISTS",
                "short_name" => "E39",
                "parent_short_code" => "sbi_status_code",
                "code" => "52641",
            ),
             array(
                "name" => "MISSING DEBIT ACCOUNT NUMBER",
                "short_name" => "E40",
                "parent_short_code" => "sbi_status_code",
                "code" => "52642",
            ),
             array(
                "name" => "MANDATORY FIELDS MISSING",
                "short_name" => "E41",
                "parent_short_code" => "sbi_status_code",
                "code" => "52643",
            ),
             array(
                "name" => "INVALID SPONSOR BANK IFSC CODE",
                "short_name" => "E42",
                "parent_short_code" => "sbi_status_code",
                "code" => "52644",
            ),
             array(
                "name" => "INVALID FILE FORMAT",
                "short_name" => "E43",
                "parent_short_code" => "sbi_status_code",
                "code" => "52645",
            ),
             array(
                "name" => "MISCELLANEOUS",
                "short_name" => "E99",
                "parent_short_code" => "sbi_status_code",
                "code" => "52646",
            ),
             array(
                "name" => "AADHAAR MAPPING DOES NOT EXISTS",
                "short_name" => "E44",
                "parent_short_code" => "sbi_status_code",
                "code" => "52647",
            ),
             array(
                "name" => "INVALID AMOUNT",
                "short_name" => "E45",
                "parent_short_code" => "sbi_status_code",
                "code" => "52648",
            ),
             array(
                "name" => "DIGITAL CERTIFICATE EXPIRED",
                "short_name" => "E46",
                "parent_short_code" => "sbi_status_code",
                "code" => "52649",
            ),
             array(
                "name" => "INVALID DESTINATION IIN",
                "short_name" => "E47",
                "parent_short_code" => "sbi_status_code",
                "code" => "52650",
            ),
             array(
                "name" => "INVALID NPCI USER ID OR USER NAME",
                "short_name" => "E48",
                "parent_short_code" => "sbi_status_code",
                "code" => "52651",
            ),
             array(
                "name" => "SPECIAL CHARACTERS FOUND",
                "short_name" => "E49",
                "parent_short_code" => "sbi_status_code",
                "code" => "52652",
            ),
            
        )
];
